name: CyberGIS Client
timezone: America/New_York
permalink: none
baseurl:
url: http://localhost
destination: _site

# Explicit excludes, including dotfiles to be safe
exclude: [.DS_Store, .git, .gitignore, .vagrant, Gruntfile.js, Vagrantfile, package.json, node_modules, backups, _assets/img/src-images]
